services:
  # RabbitMQ Service
  rabbitmq:
    image: rabbitmq:4.0-management  # Includes the RabbitMQ Management plugin
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ default port
      - "15672:15672"   # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user     # Default RabbitMQ username
      RABBITMQ_DEFAULT_PASS: password # Default RabbitMQ password
    networks:
      - app-network

  redis-node-1:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
    networks:
      - app-network
    ports:
      - "7001:6379"

  redis-node-2:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
    networks:
      - app-network
    ports:
      - "7002:6379"
  
  redis-node-3:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
    networks:
      - app-network
    ports:
      - "7003:6379"

  
  redis-node-4:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
    networks:
      - app-network
    ports:
      - "7004:6379"

  
  redis-node-5:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
    networks:
      - app-network
    ports:
      - "7005:6379"
  

  redis-node-6:
    image: bitnami/redis-cluster:latest
    container_name: redis-node-6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - 'REDIS_NODES=redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6'
      - REDIS_CLUSTER_CREATOR=yes
    networks:
      - app-network
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    ports:
      - "7006:6379"

  # Nginx Service
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "8090:8090"       # Expose Nginx on port 80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount configuration files
  #   networks:
  #     - app-network

# Define a shared network for the services
networks:
  app-network:
    driver: bridge
